/**
 * 알고리즘 태그 정적 데이터
 * solved.ac API 기준 226개 태그 (isMeta=false)
 */

export interface AlgorithmTag {
  key: string;
  nameKo: string;
  nameEn: string;
}

export const ALGORITHM_TAGS: AlgorithmTag[] = [
  { key: 'math', nameKo: '수학', nameEn: 'mathematics' },
  { key: 'implementation', nameKo: '구현', nameEn: 'implementation' },
  { key: 'dp', nameKo: '다이나믹 프로그래밍', nameEn: 'dynamic programming' },
  { key: 'data_structures', nameKo: '자료 구조', nameEn: 'data structures' },
  { key: 'graphs', nameKo: '그래프 이론', nameEn: 'graph theory' },
  { key: 'greedy', nameKo: '그리디 알고리즘', nameEn: 'greedy' },
  { key: 'string', nameKo: '문자열', nameEn: 'string' },
  { key: 'bruteforcing', nameKo: '브루트포스 알고리즘', nameEn: 'bruteforcing' },
  { key: 'graph_traversal', nameKo: '그래프 탐색', nameEn: 'graph traversal' },
  { key: 'sorting', nameKo: '정렬', nameEn: 'sorting' },
  { key: 'ad_hoc', nameKo: '애드 혹', nameEn: 'ad-hoc' },
  { key: 'geometry', nameKo: '기하학', nameEn: 'geometry' },
  { key: 'trees', nameKo: '트리', nameEn: 'tree' },
  { key: 'number_theory', nameKo: '정수론', nameEn: 'number theory' },
  { key: 'segtree', nameKo: '세그먼트 트리', nameEn: 'segment tree' },
  { key: 'binary_search', nameKo: '이분 탐색', nameEn: 'binary search' },
  { key: 'set', nameKo: '집합과 맵', nameEn: 'set / map' },
  { key: 'constructive', nameKo: '해 구성하기', nameEn: 'constructive' },
  { key: 'arithmetic', nameKo: '사칙연산', nameEn: 'arithmetic' },
  { key: 'simulation', nameKo: '시뮬레이션', nameEn: 'simulation' },
  { key: 'prefix_sum', nameKo: '누적 합', nameEn: 'prefix sum' },
  { key: 'combinatorics', nameKo: '조합론', nameEn: 'combinatorics' },
  { key: 'bfs', nameKo: '너비 우선 탐색', nameEn: 'breadth-first search' },
  { key: 'case_work', nameKo: '많은 조건 분기', nameEn: 'case work' },
  { key: 'bitmask', nameKo: '비트마스킹', nameEn: 'bitmask' },
  { key: 'shortest_path', nameKo: '최단 경로', nameEn: 'shortest path' },
  { key: 'dfs', nameKo: '깊이 우선 탐색', nameEn: 'depth-first search' },
  { key: 'hash_set', nameKo: '해시를 사용한 집합과 맵', nameEn: 'set / map by hashing' },
  { key: 'dijkstra', nameKo: '데이크스트라', nameEn: "dijkstra's" },
  { key: 'sweeping', nameKo: '스위핑', nameEn: 'sweeping' },
  { key: 'disjoint_set', nameKo: '분리 집합', nameEn: 'disjoint set' },
  { key: 'backtracking', nameKo: '백트래킹', nameEn: 'backtracking' },
  { key: 'dp_tree', nameKo: '트리에서의 다이나믹 프로그래밍', nameEn: 'dynamic programming on trees' },
  { key: 'priority_queue', nameKo: '우선순위 큐', nameEn: 'priority queue' },
  { key: 'tree_set', nameKo: '트리를 사용한 집합과 맵', nameEn: 'set / map by trees' },
  { key: 'parsing', nameKo: '파싱', nameEn: 'parsing' },
  { key: 'game_theory', nameKo: '게임 이론', nameEn: 'game theory' },
  { key: 'parametric_search', nameKo: '매개 변수 탐색', nameEn: 'parametric search' },
  { key: 'divide_and_conquer', nameKo: '분할 정복', nameEn: 'divide and conquer' },
  { key: 'two_pointer', nameKo: '두 포인터', nameEn: 'two-pointer' },
  { key: 'probability', nameKo: '확률론', nameEn: 'probability theory' },
  { key: 'stack', nameKo: '스택', nameEn: 'stack' },
  { key: 'lazyprop', nameKo: '느리게 갱신되는 세그먼트 트리', nameEn: 'segment tree with lazy propagation' },
  { key: 'primality_test', nameKo: '소수 판정', nameEn: 'primality test' },
  { key: 'flow', nameKo: '최대 유량', nameEn: 'maximum flow' },
  { key: 'dp_bitfield', nameKo: '비트필드를 이용한 다이나믹 프로그래밍', nameEn: 'dynamic programming using bitfield' },
  { key: 'offline_queries', nameKo: '오프라인 쿼리', nameEn: 'offline queries' },
  { key: 'exponentiation_by_squaring', nameKo: '분할 정복을 이용한 거듭제곱', nameEn: 'exponentiation by squaring' },
  { key: 'knapsack', nameKo: '배낭 문제', nameEn: 'knapsack' },
  { key: 'dag', nameKo: '방향 비순환 그래프', nameEn: 'directed acyclic graph' },
  { key: 'coordinate_compression', nameKo: '값 / 좌표 압축', nameEn: 'value / coordinate compression' },
  { key: 'recursion', nameKo: '재귀', nameEn: 'recursion' },
  { key: 'arbitrary_precision', nameKo: '임의 정밀도 / 큰 수 연산', nameEn: 'arbitrary precision / big integers' },
  { key: 'euclidean', nameKo: '유클리드 호제법', nameEn: 'euclidean algorithm' },
  { key: 'mst', nameKo: '최소 스패닝 트리', nameEn: 'minimum spanning tree' },
  { key: 'precomputation', nameKo: '런타임 전의 전처리', nameEn: 'precomputation' },
  { key: 'topological_sorting', nameKo: '위상 정렬', nameEn: 'topological sorting' },
  { key: 'convex_hull', nameKo: '볼록 껍질', nameEn: 'convex hull' },
  { key: 'linear_algebra', nameKo: '선형대수학', nameEn: 'linear algebra' },
  { key: 'sieve', nameKo: '에라토스테네스의 체', nameEn: 'sieve of eratosthenes' },
  { key: 'grid_graph', nameKo: '격자 그래프', nameEn: 'grid graph' },
  { key: 'bipartite_matching', nameKo: '이분 매칭', nameEn: 'bipartite matching' },
  { key: 'inclusion_and_exclusion', nameKo: '포함 배제의 원리', nameEn: 'inclusion and exclusion' },
  { key: 'lca', nameKo: '최소 공통 조상', nameEn: 'lowest common ancestor' },
  { key: 'sparse_table', nameKo: '희소 배열', nameEn: 'sparse table' },
  { key: 'randomization', nameKo: '무작위화', nameEn: 'randomization' },
  { key: 'hashing', nameKo: '해싱', nameEn: 'hashing' },
  { key: 'floyd_warshall', nameKo: '플로이드–워셜', nameEn: 'floyd–warshall' },
  { key: 'modular_multiplicative_inverse', nameKo: '모듈로 곱셈 역원', nameEn: 'modular multiplicative inverse' },
  { key: 'scc', nameKo: '강한 연결 요소', nameEn: 'strongly connected component' },
  { key: 'parity', nameKo: '홀짝성', nameEn: 'parity' },
  { key: 'traceback', nameKo: '역추적', nameEn: 'traceback' },
  { key: 'smaller_to_larger', nameKo: '작은 집합에서 큰 집합으로 합치는 테크닉', nameEn: 'smaller to larger technique' },
  { key: 'line_intersection', nameKo: '선분 교차 판정', nameEn: 'line segment intersection check' },
  { key: 'fft', nameKo: '고속 푸리에 변환', nameEn: 'fast fourier transform' },
  { key: 'calculus', nameKo: '미적분학', nameEn: 'calculus' },
  { key: 'sqrt_decomposition', nameKo: '제곱근 분할법', nameEn: 'square root decomposition' },
  { key: 'trie', nameKo: '트라이', nameEn: 'trie' },
  { key: 'deque', nameKo: '덱', nameEn: 'deque' },
  { key: 'geometry_3d', nameKo: '3차원 기하학', nameEn: 'geometry; 3d' },
  { key: 'ternary_search', nameKo: '삼분 탐색', nameEn: 'ternary search' },
  { key: 'heuristics', nameKo: '휴리스틱', nameEn: 'heuristics' },
  { key: 'euler_tour_technique', nameKo: '오일러 경로 테크닉', nameEn: 'euler tour technique' },
  { key: 'suffix_array', nameKo: '접미사 배열과 LCP 배열', nameEn: 'suffix array and lcp array' },
  { key: 'mcmf', nameKo: '최소 비용 최대 유량', nameEn: 'minimum cost maximum flow' },
  { key: 'sprague_grundy', nameKo: '스프라그–그런디 정리', nameEn: 'sprague–grundy theorem' },
  { key: 'sliding_window', nameKo: '슬라이딩 윈도우', nameEn: 'sliding window' },
  { key: 'prime_factorization', nameKo: '소인수분해', nameEn: 'prime factorization' },
  { key: 'cht', nameKo: '볼록 껍질을 이용한 최적화', nameEn: 'convex hull trick' },
  { key: 'centroid', nameKo: '센트로이드', nameEn: 'centroid' },
  { key: 'pythagoras', nameKo: '피타고라스 정리', nameEn: 'pythagoras theorem' },
  { key: 'permutation_cycle_decomposition', nameKo: '순열 사이클 분할', nameEn: 'permutation cycle decomposition' },
  { key: 'mitm', nameKo: '중간에서 만나기', nameEn: 'meet in the middle' },
  { key: 'lis', nameKo: '가장 긴 증가하는 부분 수열 문제', nameEn: 'longest increasing sequence problem' },
  { key: 'bitset', nameKo: '비트 집합', nameEn: 'bit set' },
  { key: 'kmp', nameKo: 'KMP', nameEn: 'knuth–morris–pratt' },
  { key: 'gaussian_elimination', nameKo: '가우스 소거법', nameEn: 'gaussian elimination' },
  { key: 'hld', nameKo: 'Heavy-light 분할', nameEn: 'heavy-light decomposition' },
  { key: 'linearity_of_expectation', nameKo: '기댓값의 선형성', nameEn: 'linearity of expectation' },
  { key: 'bipartite_graph', nameKo: '이분 그래프', nameEn: 'bipartite graph' },
  { key: 'difference_array', nameKo: '차분 배열 트릭', nameEn: 'difference array' },
  { key: 'polygon_area', nameKo: '다각형의 넓이', nameEn: 'area of a polygon' },
  { key: 'mfmc', nameKo: '최대 유량 최소 컷 정리', nameEn: 'max-flow min-cut theorem' },
  { key: 'centroid_decomposition', nameKo: '센트로이드 분할', nameEn: 'centroid decomposition' },
  { key: 'physics', nameKo: '물리학', nameEn: 'physics' },
  { key: 'flt', nameKo: '페르마의 소정리', nameEn: "fermat's little theorem" },
  { key: '0_1_bfs', nameKo: '0-1 너비 우선 탐색', nameEn: '0-1 bfs' },
  { key: 'eulerian_path', nameKo: '오일러 경로', nameEn: 'eulerian path / circuit' },
  { key: 'flood_fill', nameKo: '플러드 필', nameEn: 'flood-fill' },
  { key: 'articulation', nameKo: '단절점과 단절선', nameEn: 'articulation points and bridges' },
  { key: '2_sat', nameKo: '2-sat', nameEn: '2-sat' },
  { key: 'queue', nameKo: '큐', nameEn: 'queue' },
  { key: 'functional_graph', nameKo: '함수형 그래프', nameEn: 'functional graph' },
  { key: 'tsp', nameKo: '외판원 순회 문제', nameEn: 'travelling salesman problem' },
  { key: 'pigeonhole_principle', nameKo: '비둘기집 원리', nameEn: 'pigeonhole principle' },
  { key: 'deque_trick', nameKo: '덱을 이용한 구간 최댓값 트릭', nameEn: 'deque range maximum trick' },
  { key: 'rerooting', nameKo: '트리에서의 전방향 다이나믹 프로그래밍', nameEn: 'rerooting on trees' },
  { key: 'planar_graph', nameKo: '평면 그래프', nameEn: 'planar graph' },
  { key: 'generating_function', nameKo: '생성 함수', nameEn: 'generating function' },
  { key: 'pst', nameKo: '퍼시스턴트 세그먼트 트리', nameEn: 'persistent segment tree' },
  { key: 'euler_phi', nameKo: '오일러 피 함수', nameEn: 'euler totient function' },
  { key: 'point_in_convex_polygon', nameKo: '볼록 다각형 내부의 점 판정', nameEn: 'point in convex polygon check' },
  { key: 'bcc', nameKo: '이중 연결 요소', nameEn: 'biconnected component' },
  { key: 'crt', nameKo: '중국인의 나머지 정리', nameEn: 'chinese remainder theorem' },
  { key: 'dp_digit', nameKo: '자릿수를 이용한 다이나믹 프로그래밍', nameEn: 'digit dp' },
  { key: 'linked_list', nameKo: '연결 리스트', nameEn: 'linked list' },
  { key: 'angle_sorting', nameKo: '각도 정렬', nameEn: 'angle sorting' },
  { key: 'harmonic_number', nameKo: '조화수', nameEn: 'harmonic number' },
  { key: 'mo', nameKo: "mo's", nameEn: "mo's" },
  { key: 'tree_diameter', nameKo: '트리의 지름', nameEn: 'diameter of a tree' },
  { key: 'cactus', nameKo: '선인장', nameEn: 'cactus' },
  { key: 'invariant', nameKo: '불변량 찾기', nameEn: 'finding invariants' },
  { key: 'bellman_ford', nameKo: '벨만–포드', nameEn: 'bellman–ford' },
  { key: 'extended_euclidean', nameKo: '확장 유클리드 호제법', nameEn: 'extended euclidean algorithm' },
  { key: 'splay_tree', nameKo: '스플레이 트리', nameEn: 'splay tree' },
  { key: 'maximum_subarray', nameKo: '최대 부분 배열 문제', nameEn: 'maximum subarray' },
  { key: 'divide_and_conquer_optimization', nameKo: '분할 정복을 사용한 최적화', nameEn: 'divide and conquer optimization' },
  { key: 'pbs', nameKo: '병렬 이분 탐색', nameEn: 'parallel binary search' },
  { key: 'dp_sum_over_subsets', nameKo: '부분집합의 합 다이나믹 프로그래밍', nameEn: 'sum over subsets dynamic programming' },
  { key: 'half_plane_intersection', nameKo: '반평면 교집합', nameEn: 'half plane intersection' },
  { key: 'rotating_calipers', nameKo: '회전하는 캘리퍼스', nameEn: 'rotating calipers' },
  { key: 'euler_characteristic', nameKo: '오일러 지표 (χ=V-E+F)', nameEn: 'euler characteristic (χ=v-e+f)' },
  { key: 'multi_segtree', nameKo: '다차원 세그먼트 트리', nameEn: 'multidimensional segment tree' },
  { key: 'regex', nameKo: '정규 표현식', nameEn: 'regular expression' },
  { key: 'slope_trick', nameKo: '함수 개형을 이용한 최적화', nameEn: 'slope trick' },
  { key: 'dp_deque', nameKo: '덱을 이용한 다이나믹 프로그래밍', nameEn: 'dynamic programming using a deque' },
  { key: 'manacher', nameKo: '매내처', nameEn: "manacher's" },
  { key: 'pollard_rho', nameKo: '폴라드 로', nameEn: 'pollard rho' },
  { key: 'miller_rabin', nameKo: '밀러–라빈 소수 판별법', nameEn: 'miller–rabin' },
  { key: 'aho_corasick', nameKo: '아호-코라식', nameEn: 'aho-corasick' },
  { key: 'lcs', nameKo: '최장 공통 부분 수열 문제', nameEn: 'longest common subsequence' },
  { key: 'mobius_inversion', nameKo: '뫼비우스 반전 공식', nameEn: 'möbius inversion' },
  { key: 'tree_isomorphism', nameKo: '트리 동형 사상', nameEn: 'tree isomorphism' },
  { key: 'merge_sort_tree', nameKo: '머지 소트 트리', nameEn: 'merge sort tree' },
  { key: 'link_cut_tree', nameKo: '링크/컷 트리', nameEn: 'link/cut tree' },
  { key: 'cartesian_tree', nameKo: '데카르트 트리', nameEn: 'cartesian tree' },
  { key: 'numerical_analysis', nameKo: '수치해석', nameEn: 'numerical analysis' },
  { key: 'dp_connection_profile', nameKo: '커넥션 프로파일을 이용한 다이나믹 프로그래밍', nameEn: 'dynamic programming using connection profile' },
  { key: 'point_in_non_convex_polygon', nameKo: '오목 다각형 내부의 점 판정', nameEn: 'point in non-convex polygon check' },
  { key: 'rabin_karp', nameKo: '라빈–카프', nameEn: 'rabin–karp' },
  { key: 'simulated_annealing', nameKo: '담금질 기법', nameEn: 'simulated annealing' },
  { key: 'hall', nameKo: '홀의 결혼 정리', nameEn: "hall's theorem" },
  { key: 'z', nameKo: 'z', nameEn: 'z' },
  { key: 'statistics', nameKo: '통계학', nameEn: 'statistics' },
  { key: 'berlekamp_massey', nameKo: '벌리캠프–매시', nameEn: 'berlekamp–massey' },
  { key: 'offline_dynamic_connectivity', nameKo: '오프라인 동적 연결성 판정', nameEn: 'offline dynamic connectivity' },
  { key: 'geometric_boolean_operations', nameKo: '도형에서의 불 연산', nameEn: 'boolean operations on geometric objects' },
  { key: 'xor_basis', nameKo: '배타적 논리합 기저 (gf(2))', nameEn: 'xor basis (gf(2))' },
  { key: 'li_chao_tree', nameKo: '리–차오 트리', nameEn: 'li–chao tree' },
  { key: 'alien', nameKo: 'Aliens 트릭', nameEn: 'aliens trick' },
  { key: 'hungarian', nameKo: '헝가리안', nameEn: 'hungarian' },
  { key: 'tree_compression', nameKo: '트리 압축', nameEn: 'tree compression' },
  { key: 'linear_programming', nameKo: '선형 계획법', nameEn: 'linear programming' },
  { key: 'beats', nameKo: '세그먼트 트리 비츠', nameEn: 'segment tree beats' },
  { key: 'lucas', nameKo: '뤼카 정리', nameEn: 'lucas theorem' },
  { key: 'duality', nameKo: '쌍대성', nameEn: 'duality' },
  { key: 'voronoi', nameKo: '보로노이 다이어그램', nameEn: 'voronoi diagram' },
  { key: 'circulation', nameKo: '서큘레이션', nameEn: 'circulation' },
  { key: 'green', nameKo: '그린 정리', nameEn: "green's theorem" },
  { key: 'dual_graph', nameKo: '쌍대 그래프', nameEn: 'dual graph' },
  { key: 'polynomial_interpolation', nameKo: '다항식 보간법', nameEn: 'polynomial interpolation' },
  { key: 'general_matching', nameKo: '일반적인 매칭', nameEn: 'general matching' },
  { key: 'monotone_queue_optimization', nameKo: '단조 큐를 이용한 최적화', nameEn: 'monotone queue optimization' },
  { key: 'cdq', nameKo: 'cdq 분할 정복', nameEn: 'cdq' },
  { key: 'pick', nameKo: '픽의 정리', nameEn: "pick's theorem" },
  { key: 'matroid', nameKo: '매트로이드', nameEn: 'matroid' },
  { key: 'kitamasa', nameKo: '다항식을 이용한 선형점화식 계산', nameEn: 'linear recurrence calculation by polynomials' },
  { key: 'suffix_tree', nameKo: '접미사 트리', nameEn: 'suffix tree' },
  { key: 'discrete_log', nameKo: '이산 로그', nameEn: 'discrete logarithm' },
  { key: 'geometry_hyper', nameKo: '4차원 이상의 기하학', nameEn: 'geometry; hyperdimensional' },
  { key: 'tree_decomposition', nameKo: '트리 분할', nameEn: 'tree decomposition' },
  { key: 'min_enclosing_circle', nameKo: '최소 외접원', nameEn: 'minimum enclosing circle' },
  { key: 'differential_cryptanalysis', nameKo: '차분 공격', nameEn: 'differential cryptanalysis' },
  { key: 'utf8', nameKo: 'utf-8 입력 처리', nameEn: 'utf-8 inputs' },
  { key: 'burnside', nameKo: '번사이드 보조정리', nameEn: "burnside's lemma" },
  { key: 'bulldozer', nameKo: 'bulldozer 트릭', nameEn: 'bulldozer trick' },
  { key: 'degree_sequence', nameKo: '차수열', nameEn: 'degree sequence' },
  { key: 'top_tree', nameKo: '탑 트리', nameEn: 'top tree' },
  { key: 'dominator_tree', nameKo: '도미네이터 트리', nameEn: 'dominator tree' },
  { key: 'bidirectional_search', nameKo: '양방향 탐색', nameEn: 'bidirectional search' },
  { key: 'lgv', nameKo: '린드스트롬–게셀–비엔노 보조정리', nameEn: 'lindström–gessel–viennot lemma' },
  { key: 'knuth_x', nameKo: '크누스 X', nameEn: "knuth's x" },
  { key: 'dancing_links', nameKo: '춤추는 링크', nameEn: 'dancing links' },
  { key: 'discrete_sqrt', nameKo: '이산 제곱근', nameEn: 'discrete square root' },
  { key: 'palindrome_tree', nameKo: '회문 트리', nameEn: 'palindrome tree' },
  { key: 'gradient_descent', nameKo: '경사 하강법', nameEn: 'gradient descent' },
  { key: 'rope', nameKo: '로프', nameEn: 'rope' },
  { key: 'pisano', nameKo: '피사노 주기', nameEn: 'pisano period' },
  { key: 'floor_sum', nameKo: '유리 등차수열의 내림 합', nameEn: 'sum of floor of rational arithmetic sequence' },
  { key: 'stable_marriage', nameKo: '안정 결혼 문제', nameEn: 'stable marriage problem' },
  { key: 'bayes', nameKo: '베이즈 정리', nameEn: 'bayes theorem' },
  { key: 'delaunay', nameKo: '델로네 삼각분할', nameEn: 'delaunay triangulation' },
  { key: 'knuth', nameKo: '크누스 최적화', nameEn: 'knuth optimization' },
  { key: 'bitset_lcs', nameKo: '비트 집합을 이용한 최장 공통 부분 수열 최적화', nameEn: 'longest common subsequence using bit sets' },
  { key: 'kinetic_segtree', nameKo: '키네틱 세그먼트 트리', nameEn: 'kinetic segment tree' },
  { key: 'multipoint_evaluation', nameKo: '다중 대입값 계산', nameEn: 'multipoint evaluation' },
  { key: 'dial', nameKo: '다이얼', nameEn: 'dial' },
  { key: 'birthday', nameKo: '생일 문제', nameEn: 'birthday problem' },
  { key: 'hirschberg', nameKo: '히르쉬버그', nameEn: "hirschberg's" },
  { key: 'chordal_graph', nameKo: '현 그래프', nameEn: 'chordal graph' },
  { key: 'lte', nameKo: '지수승강 보조정리', nameEn: 'lifting the exponent lemma' },
  { key: 'directed_mst', nameKo: '유향 최소 스패닝 트리', nameEn: 'directed minimum spanning tree' },
  { key: 'stoer_wagner', nameKo: '스토어–바그너', nameEn: 'stoer–wagner' },
  { key: 'hackenbush', nameKo: '하켄부시 게임', nameEn: 'hackenbush' },
  { key: 'majority_vote', nameKo: '보이어–무어 다수결 투표', nameEn: 'boyer–moore majority vote' },
  { key: 'rb_tree', nameKo: '레드-블랙 트리', nameEn: 'red-black tree' },
];

/**
 * 태그 검색 (한글/영문/key 모두 지원)
 */
export function searchAlgorithmTags(
  query: string,
  tags: AlgorithmTag[] = ALGORITHM_TAGS
): AlgorithmTag[] {
  const normalizedQuery = query.toLowerCase().trim();
  if (!normalizedQuery) return tags;

  return tags.filter(
    (tag) =>
      tag.key.toLowerCase().includes(normalizedQuery) ||
      tag.nameKo.toLowerCase().includes(normalizedQuery) ||
      tag.nameEn.toLowerCase().includes(normalizedQuery)
  );
}

/**
 * key로 태그 찾기
 */
export function getTagByKey(key: string): AlgorithmTag | undefined {
  return ALGORITHM_TAGS.find((tag) => tag.key === key);
}

/**
 * 여러 key로 태그 한글 이름 배열 반환
 */
export function getTagNames(keys: string[]): string[] {
  return keys
    .map((key) => getTagByKey(key)?.nameKo)
    .filter((name): name is string => !!name);
}
